[package]
name = "lichess"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess-core = { path = "../core" }
chrono = { version = "0.4.33", default-features = false, features = ["clock"] }
console-subscriber = "0.2.0"
eyre = "0.6.12"
fern = { version = "0.6.2", features = ["colored"] }
futures = { version = "0.3.30", default-features = false, features = ["std"] }
log = "0.4.20"
rand = "0.8.5"
rayon = "1.8.1"
reqwest = { version = "0.11.24", features = ["json", "stream"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "tracing"] }
tokio-stream = "0.1.14"
tracing = "0.1.40"
