[package]
name = "wasm"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.92"
chess-core = { path = "../core" }
js-sys = "0.3.69"
console_error_panic_hook = "0.1.7"
